ServerAddress = 127.0.0.1
ServerPort = 4444

### Client application ###
Client.DefaultLanguage = english
Client.AvailableLanguages = english

### Frame ###
Client.Frame.title=org.game.eternity2.client.EternityClient

### Menu Bar ###
Client.MenuBar.accessible_description=Eternity 2 Client application menu bar

### File Menu ###
Client.FileMenu.file.labelAndMnemonic=&File
Client.FileMenu.accessible_description=File Menu
Client.FileMenu.open.labelAndMnemonic=&Open
Client.FileMenu.open_accessible_description=Opening a file
Client.FileMenu.save.labelAndMnemonic=&Save
Client.FileMenu.save_accessible_description=Saving a file
Client.FileMenu.save_as.labelAndMnemonic=Save &As...
Client.FileMenu.save_as_accessible_description=Saving a file with a new name
Client.FileMenu.exit.labelAndMnemonic=E&xit
Client.FileMenu.exit_accessible_description=Exit the Eternity 2 Client application

### Options Menu ###
Client.OptionsMenu.options.labelAndMnemonic=O&ptions
Client.OptionsMenu.options_accessible_description=Options Menu
Client.OptionsMenu.tooltip.labelAndMnemonic=Enable &Tool Tips
Client.OptionsMenu.tooltip_accessible_description=Enable or disable tool tips
Client.OptionsMenu.dragEnabled.labelAndMnemonic=Enable &Drag Support
Client.OptionsMenu.dragEnabled_accessible_description=Enable or disable drag support

## About Menu ###
Client.AboutMenu.about.labelAndMnemonic=A&bout
Client.FileMenu.about_accessible_description=Find out about the Eternity 2 Client application

## About box ###
Client.AboutBox.title=About Eternity 2 Client application
Client.AboutBox.ok_button_text=OK
Client.AboutBox.accessible_description=Eternity 2 Client application is Copyright (c) 2022, Silvere Martin-Michiellot. All rights reserved.

### Status ###
Client.Status.loading=Loading:
Client.Status.popupMenuAccessible=Press Shift-F10 to activate popup menu

### Server application ###
Server.DefaultLanguage = english
Server.AvailableLanguages = english

### Frame ###
Server.Frame.title=org.game.eternity2.server.EternityCServer

### Menu Bar ###
Server.MenuBar.accessible_description=Eternity 2 Server application menu bar

### File Menu ###
Server.FileMenu.file.labelAndMnemonic=&File
Server.FileMenu.accessible_description=File Menu
Server.FileMenu.open.labelAndMnemonic=&Open
Server.FileMenu.open_accessible_description=Opening a file
Server.FileMenu.save.labelAndMnemonic=&Save
Server.FileMenu.save_accessible_description=Saving a file
Server.FileMenu.save_as.labelAndMnemonic=Save &As...
Server.FileMenu.save_as_accessible_description=Saving a file with a new name
Server.FileMenu.exit.labelAndMnemonic=E&xit
Server.FileMenu.exit_accessible_description=Exit the Eternity 2 Server application

### Options Menu ###
Server.OptionsMenu.options.labelAndMnemonic=O&ptions
Server.OptionsMenu.options_accessible_description=Options Menu
Server.OptionsMenu.tooltip.labelAndMnemonic=Enable &Tool Tips
Server.OptionsMenu.tooltip_accessible_description=Enable or disable tool tips
Server.OptionsMenu.dragEnabled.labelAndMnemonic=Enable &Drag Support
Server.OptionsMenu.dragEnabled_accessible_description=Enable or disable drag support

## About Menu ###
Server.AboutMenu.about.labelAndMnemonic=A&bout
Server.FileMenu.about_accessible_description=Find out about the Eternity 2 Server application

## About box ###
Server.AboutBox.title=About Eternity 2 Server application
Server.AboutBox.ok_button_text=OK
Server.AboutBox.accessible_description=Eternity 2 Server application is Copyright (c) 2022, Silvere Martin-Michiellot. All rights reserved.

### Status ###
Server.Status.loading=Loading:
Server.Status.popupMenuAccessible=Press Shift-F10 to activate popup menu

